import { Josefin_Sans } from "next/font/google";
import Header from "./_components/Header";
import "@/app/_styles/globals.css";
import PageTransition from "./_components/PageTransition";
import StairTransition from "./_components/StairTransition";
import { Toaster } from "react-hot-toast";

const Josefin = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Josefin.className} h-screen bg-primary-950 text-primary-100 flex flex-col antialiased`}
      >
        <Header />
        <StairTransition />
        <PageTransition className="w-full">{children}</PageTransition>
        <Toaster
          position="top-center"
          gutter={12}
          containerStyle={{ margin: "8px" }}
          toastOptions={{
            success: {
              duration: 5000,
            },
            error: {
              duration: 5000,
            },
            style: {
              fontSize: "16px",
              maxWidth: "500",
              padding: "16px 24px",
              backgroundColor: "#C69963",
              color: "#141C24",
            },
          }}
        />
      </body>
    </html>
  );
}
